/*
 * CPC SISTEMAS
 */
package primeridea.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import primeridea.model.Producto;

/**
 *
 * @author gandhi.aguirre
 */
public class MenuCompra extends VentanaPersonalizada {
    private List<Producto> inventario; 
    private ActionListener origen; 
    /**
     * Creates new form MenuCompra
     */
    public MenuCompra(List<Producto> productos, ActionListener origen) {
        super("Tienda - Compras");
        inventario = productos; 
        this.origen = origen; 
        cargarProductos(productos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    public void cargarProductos(List<Producto> productos){
        for(Producto producto : productos){
            JButton nBoton = new JButton(producto.toString());
            nBoton.setName("A,"+producto.getNombre());
            nBoton.addActionListener(origen);
            jPanel1.add(nBoton);
        }
    }

    @Override
    public void definirElementosPropios() {
        initComponents();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
    
    }

    public void setInventario(List<Producto> inventario) {
        this.inventario = inventario;
    }
    
    
}
